import LogoKK from './Logo KafeKoding 1.png'
import LogoHero from './Programmer-cuate 1.png'
import Rectangle1 from './Rectangle 35.png'
import Rectangle2 from './Rectangle 36.png'
import Rectangle3 from './Rectangle 37.png'
import Rectangle4 from './Rectangle 38.png'
import PlatformGroup1 from './Group 180.png'
import PlatformGroup2 from './Group 183.png'
import PlatformGroup3 from './Group 184.png'
import Rectangle5 from './Rectangle 52.png'
import Rectangle6 from './Rectangle 53.png'
import Rectangle7 from './Rectangle 54.png'
import LogoHTML from './HTML 1.png'
import LogoPHP from './PHP 1.png'
import LogoLAravel from './Laravel 1.png'
import LogoMsql from './kisspng-mysql-logo-database-join-portable-network-graphics-lee-qixian-about-me-5b632d94056496 1.png'
export{LogoKK,LogoHero,Rectangle1,Rectangle2,Rectangle3,Rectangle4,PlatformGroup1,PlatformGroup2,PlatformGroup3,Rectangle5,Rectangle6,Rectangle7,LogoHTML,LogoLAravel,LogoMsql,LogoPHP}