import LogoKK from './Logo KafeKoding 1.png'
import LogoHero from './Programmer-cuate 1.png'
import Rectangle1 from './Rectangle 35.png'
import Rectangle2 from './Rectangle 36.png'
import Rectangle3 from './Rectangle 37.png'
import Rectangle4 from './Rectangle 38.png'
import PlatformGroup1 from './Group 180.png'
import PlatformGroup2 from './Group 183.png'
import PlatformGroup3 from './Group 184.png'
export{LogoKK,LogoHero,Rectangle1,Rectangle2,Rectangle3,Rectangle4,PlatformGroup1,PlatformGroup2,PlatformGroup3}